openapi: '3.0.2'
info:
  title: MTG API
  version: '1.0'
servers:
  - url: http://localhost:3000/
paths:
  /api/card/page/{page}:
    get:
      parameters:
        - in: path
          name: page
          schema:
            type: integer
          required: true
        - in: query
          name: name
          schema:
            type: string
        - in: query
          name: color
          schema:
            type: array
            items:
              type: string
              enum:
                - B
                - W
                - U
                - G
                - R
                - NONE
        - in: query
          name: cost
          schema:
            type: string
            # pattern: /^(gte|lte|equals):[0-9]*/ なんかvalidation通らないのでとりあえずコメントアウト
          allowReserved: true
        - in: query
          name: types
          schema:
            type: array
            items:
              type: string
        - in: query
          name: rarity
          schema:
            type: array
            items:
              type: string
        - in: query
          name: setCode
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                nullable: false
                $ref: '#/components/schemas/CardPagination'
      operationId: getList
      description: 'カードの一覧を取得する'
      tags:
        - card

  /api/card/detail/{uuid}:
    get:
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/CardDetail'
      operationId: getOne
      description: 'カードの詳細を取得する'
      tags:
        - card

  /api/set:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Set'
      operationId: getAllSet
      description: 'セットの一覧'
      tags:
        - card

components:
  schemas:
    CardPagination:
      type: object
      properties:
        page:
          type: integer
        pageSize:
          type: integer
        count:
          type: integer
        list:
          type: array
          items:
            $ref: '#/components/schemas/Card'
      required:
        - page
        - pageSize
        - count
        - list
    Card:
      type: object
      required:
        - uuid
        - name
      properties:
        uuid:
          type: string
        name:
          type: string
        manaCost:
          type: string
          nullable: true
        rarity:
          type: string
          nullable: true
        setCode:
          type: string
          nullable: true
        otherFaceUuid:
          type: string
          nullable: true

    CardDetail:
      type: object
      required:
        - uuid
        - name
      properties:
        uuid:
          type: string
        name:
          type: string
        manaCost:
          type: string
          nullable: true
        manaValue:
          type: integer
          nullable: true
        text:
          type: string
          nullable: true
        flavorText:
          type: string
          nullable: true
        types:
          type: array
          items:
            type: string
          nullable: true
        superTypes:
          type: array
          items:
            type: string
          nullable: true
        subTypes:
          type: array
          items:
            type: string
          nullable: true
        rarity:
          type: string
        power:
          type: string
          nullable: true
        toughness:
          type: string
          nullable: true
        loyalty:
          type: string
          nullable: true
        setCode:
          type: string
        otherFaceUuid:
          type: string
          nullable: true

    Set:
      type: object
      required:
        - code
        - name
      properties:
        code:
          type: string
        name:
          type: string