openapi: '3.0.2'
info:
  title: MTG API
  version: '1.0'
servers:
  - url: http://localhost:3000/
paths:
  /api/card/page/{page}:
    get:
      parameters:
        - in: path
          name: page
          schema:
            type: integer
          required: true
        - in: query
          name: name
          schema:
            type: string
        - in: query
          name: color
          schema:
            type: array
            items:
              type: string
              enum:
                - B
                - W
                - U
                - G
                - R
                - NONE
        - in: query
          name: cost
          schema:
            type: string
            # pattern: /^(gte|lte|equals):[0-9]*/ なんかvalidation通らないのでとりあえずコメントアウト
          allowReserved: true
        - in: query
          name: types
          schema:
            type: array
            items:
              type: string
        - in: query
          name: rarity
          schema:
            type: array
            items:
              type: string
        - in: query
          name: setCode
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                type: object
                properties:
                  page:
                    type: integer
                  pageSize:
                    type: integer
                  count:
                    type: integer
                  list:
                    type: array
                    items:
                      $ref: '#/components/schemas/Card'

  /api/card/detail/{uuid}:
    get:
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                type: object
                $ref: '#/components/schemas/CardDetail'

components:
  schemas:
    Card:
      type: object
      required:
        - uuid
        - name
      properties:
        uuid:
          type: string
        name:
          type: string
        manaCost:
          type: string
          nullable: true
        rarity:
          type: string
          nullable: true
        setCode:
          type: string
          nullable: true
        otherFaceUuid:
          type: string
          nullable: true
    CardDetail:
      type: object
      required:
        - uuid
        - name
        - types
      properties:
        uuid:
          type: string
        name:
          type: string
        manaCost:
          type: string
        manaValue:
          type: integer
        text:
          type: string
        flavorText:
          type: string
        types:
          type: array
          items:
            type: string
        superTypes:
          type: array
          items:
            type: string
        subTypes:
          type: array
          items:
            type: string
        rarity:
          type: string
        power:
          type: string
        toughness:
          type: string
        loyalty:
          type: string
        setCode:
          type: string
        otherFaceUuid:
          type: string
        